#Manifest file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    teir: frontend
    project:  expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      teir: frontend
      project:  expense
  template:
    metadata:
      labels:
        app: frontend
        teir: frontend
        project:  expense
    spec:
      containers:
      - name: frontend
      # changes the image
        image: sriteja90/frontend:1.0.1 
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
      app: frontend
      teir: frontend
      project:  expense
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
