#Manifest file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    teir: mysql
    project:  expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      teir: mysql
      project:  expense
  template:
    metadata:
      labels:
        app: mysql
        teir: mysql
        project:  expense
    spec:
      containers:
      - name: mysql
        image: sriteja90/mysql:1.0.0
